service: serverless-kanban
app: serverless-kanban
org: feakuru

frameworkVersion: '2'

plugins:
  - serverless-python-requirements
package:
  exclude:
    - requirements.txt

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-west-1 
  environment:
    DB_HOST: feaku.ru
    DB_NAME: kanban
    DB_USER: kanban_user
    DB_PASSWORD: kanban_password
    TASK_HOURLY_COST: 100

functions:
  list_tasks:
    handler: handlers.list_tasks
    timeout: 10
    events:
      - http:
          path: /tasks
          method: get
          cors: true
          integration: lambda
  get_task:
    handler: handlers.get_task
    timeout: 10
    events:
      - http:
          path: /tasks/{task_id}
          method: get
          cors: true
          integration: lambda
          request:
            paths:
              todo_id: true
  create_task:
    handler: handlers.create_task
    timeout: 10
    events:
      - http:
          path: /tasks
          method: post
          cors: true
          integration: lambda
  start_task:
    handler: handlers.start_task
    timeout: 10
    events:
      - http:
          path: /tasks/{task_id}/start
          method: get
          cors: true
          integration: lambda
          request:
            paths:
              todo_id: true
  finish_task:
    handler: handlers.finish_task
    timeout: 10
    events:
      - http:
          path: /tasks/{task_id}/finish
          method: get
          cors: true
          integration: lambda
          request:
            paths:
              todo_id: true
