service: serverless-kanban
app: serverless-kanban
org: feakuru

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-west-1

functions:
  list_tasks:
    handler: handlers.list_tasks
    events:
      - http:
          path: /tasks
          method: get
          cors: true
  get_task:
    handler: handlers.get_task
    events:
      - http:
          path: /tasks
          method: post
          cors: true
  create_task:
    handler: handlers.create_task
    events:
      - http:
          path: /tasks/{task_id}
          method: get
          cors: true
